### ISSUE TITLE
Game Setup View Storyboard

### ISSUE THREAD

**Issue by donnywdavis** [donnywdavis/Word-Jive#3]
Table View

Allow user to specify:
Width (2 - 20)
Height (2 - 20)
Words (5 - 30)
Min Length of Word (2)
Max Length of Word (28)

Play button
    saves settings
    *Day Two: submits a post request

**Comment by allenspicer** [comment]
Table View

Allow user to specify:
Width (2 - 20)
Height (2 - 20)
Words (5 - 30)
Min Length of Word (2)
Max Length of Word (28)

(Capability aka orientation) 
Horizontal Words
Vertical Words
Angular Words
Whatever Words

Play button
